services:
  discord_chatgpt:
    build: .
    container_name: "discord_chatgpt"
    user: root
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./data:/usr/src/app/data
      - ./env.json:/usr/src/app/env.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
